import type { ReactElement } from "react"

/**
 * The head links of every site's favicon set, which each app keeps under the
 * same names in its public folder (generated by `apps/brand/scripts/favicons.ts`).
 * The ICO declares its 32 px size, so browsers that read SVG icons do not
 * download it as well.
 *
 * @returns The icon, Apple touch icon, and manifest links.
 */
export function FaviconLinks(): ReactElement {
  return (
    <>
      <link href="/favicon.ico" rel="icon" sizes="32x32" />
      <link href="/icon.svg" rel="icon" type="image/svg+xml" />
      <link href="/apple-touch-icon.png" rel="apple-touch-icon" />
      <link href="/manifest.webmanifest" rel="manifest" />
    </>
  )
}
