import type { BrandId } from "@sebastian-websites/web-core"

import consultingAppleTouch from "./assets/favicons/consulting/apple-touch-icon.png?url&no-inline"
import consultingIco from "./assets/favicons/consulting/favicon.ico?url&no-inline"
import consulting192 from "./assets/favicons/consulting/icon-192.png?url&no-inline"
import consulting512 from "./assets/favicons/consulting/icon-512.png?url&no-inline"
import consultingMask from "./assets/favicons/consulting/icon-mask.png?url&no-inline"
import consultingSvg from "./assets/favicons/consulting/icon.svg?url&no-inline"
import softwareAppleTouch from "./assets/favicons/software/apple-touch-icon.png?url&no-inline"
import softwareIco from "./assets/favicons/software/favicon.ico?url&no-inline"
import software192 from "./assets/favicons/software/icon-192.png?url&no-inline"
import software512 from "./assets/favicons/software/icon-512.png?url&no-inline"
import softwareMask from "./assets/favicons/software/icon-mask.png?url&no-inline"
import softwareSvg from "./assets/favicons/software/icon.svg?url&no-inline"

/** One brand's icon files; Vite hashes their names so the CDN can keep them forever. */
export type FaviconSet = {
  readonly appleTouch: string
  /** The 32 px ICO for browsers without SVG icons. */
  readonly ico: string
  readonly icon192: string
  readonly icon512: string
  readonly mask: string
  readonly svg: string
}

/**
 * The hashed favicon files per brand, generated by `apps/brand/scripts/favicons.ts`.
 * Each app also keeps an unhashed `favicon.ico` in its public folder, because
 * some clients request `/favicon.ico` without reading a page (a PDF opened in a
 * tab, feed readers); everything the page links is hashed.
 */
export const FAVICONS = {
  consulting: {
    appleTouch: consultingAppleTouch,
    ico: consultingIco,
    icon192: consulting192,
    icon512: consulting512,
    mask: consultingMask,
    svg: consultingSvg,
  },
  software: {
    appleTouch: softwareAppleTouch,
    ico: softwareIco,
    icon192: software192,
    icon512: software512,
    mask: softwareMask,
    svg: softwareSvg,
  },
} as const satisfies Readonly<Record<BrandId, FaviconSet>>

/** The web manifest's stable address, which browsers use to identify it. */
export const WEB_MANIFEST_PATH = "/manifest.webmanifest"

/**
 * The web manifest of a site: its name and the brand's three manifest icons.
 * Each app serves it from a prerendered route at `WEB_MANIFEST_PATH`.
 *
 * @param brand - The brand whose icons the site shows.
 * @param name - The site's name, as an installed app would show it.
 * @returns The manifest as JSON.
 */
export function createWebManifest(brand: BrandId, name: string): string {
  const icons = FAVICONS[brand]
  return `${JSON.stringify(
    {
      icons: [
        { sizes: "192x192", src: icons.icon192, type: "image/png" },
        { purpose: "maskable", sizes: "512x512", src: icons.mask, type: "image/png" },
        { sizes: "512x512", src: icons.icon512, type: "image/png" },
      ],
      name,
    },
    null,
    2
  )}\n`
}
